@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
//# @prompt username
GET http://{{host}} HTTP/1.1

### Login and receive JWT Token
POST http://{{host}}/api/users/login
Content-Type: application/json

{
  "phoneNumber": "36250105",
  "password": "123"
}



### Register User
POST http://{{host}}/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM2MzYzNjM2IiwiaWF0IjoxNzQ3NTg2NjY1LCJleHAiOjE3NTAxNzg2NjV9.ZwxmD9Jy4GY1otitNys2nrk0RHs8M0b_6JOUOp5sUNE

{
  "phoneNumber": "36363636",
  "email": "sde@gmail.com",
  "password": "123"
}

### Login User
# @name user
POST http://{{host}}/api/users/login
Content-Type: application/json

{
  "phoneNumber": "36351161",
  "password": "123"
}

### Login admin
# @name admin
POST http://{{host}}/api/users/login
Content-Type: application/json

{
  "loginInput": "36351161",
  "password": "123"
}

### Get All Users (Admin Only)
GET http://{{host}}/api/users
Authorization: Bearer {{admin.response.body.token}}

### Middleware to Set JWT Token (for non-admin user)
### Unauthorized Access to Get All Users
GET http://{{host}}/api/users
Authorization: Bearer {{user.response.body.token}}

### Middleware to Set JWT Token (for admin user)
### Invalid Login
POST http://{{host}}/api/users/login
Content-Type: application/json

{
  "email": "invalid@example.com",
  "password": "wrongpassword"
}


### Get All Users Without Token
GET http://{{host}}/api/users

### send otp
POST http://{{host}}/api/otp/send-otp?reset
Content-Type: application/json

{
  "phoneNumber": "36363636"
}

### verify otp
POST http://{{host}}/api/otp/verify-otp
Content-Type: application/json

{
  "phoneNumber": "36363636",
  "otp": "133789"
}

### Get all blood requests
GET http://{{host}}/api/blood-requests
Authorization: Bearer {{user.response.body.token}}

### Create a new blood request
# @name bloodRequest
POST http://{{host}}/api/blood-requests
Content-Type: application/json
Authorization: Bearer {{user.response.body.token}}

{
  "bloodType": "A-",
  "location": "Lexeiba 2",
  "deadline": "2025-05-24",
  "description": "Urgent blood needed",
  "isUrgent": true,
  "contactMethods": [
    {
      "method": "phone",
      "number": "36250105"
    },
    {
      "method": "whatsapp",
      "number": "36250105"
    }
  ]
}

### Get a blood request by ID
GET http://{{host}}/api/blood-requests/{{bloodRequest.response.body._id}}
Authorization: Bearer {{user.response.body.token}}

### Update a blood request
PUT http://{{host}}/api/blood-requests/{{bloodRequest.response.body._id}}
Content-Type: application/json
Authorization: Bearer {{user.response.body.token}}

{
  "description": "Updated description",
  "isUrgent": false
}

### Delete a blood request
DELETE http://{{host}}/api/blood-requests/{{bloodRequest.response.body._id}}
Authorization: Bearer {{user.response.body.token}}

### Send a message
POST http://localhost:5000/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTYyODVjZmU1NzI1ODYxMWRlYzkzZCIsImlhdCI6MTc1MjAwMDI1MywiZXhwIjoxNzU0NTkyMjUzfQ.QvUuk8yfR_gBbMh11FjbHRzGAwGrW-VQaspLC6nOHaY

{
  "sender": "664a3db7bb028265c2a510d4",
  "recipient": "664a3db7bb028265c2a510d7",
  "content": "Hello, this is a test message!"
}
